[package]
name = "node-inspect"
version = "0.8.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1" }
derive_more = "0.99"
log = "0.4.8"
tc-cli = { version = "0.8.0", path = "../../../client/cli" }
tc-client-api = { version = "2.0.0", path = "../../../client/api" }
tc-service = { version = "0.8.0", default-features = false, path = "../../../client/service" }
tp-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
tp-core = { version = "2.0.0", path = "../../../primitives/core" }
tp-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
structopt = "0.3.8"
