[package]
name = "tp-state-machine"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Tetcore State Machine"
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/tp-state-machine"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { version = "0.4.11", optional = true }
thiserror = { version = "1.0.21", optional = true }
parking_lot = { version = "0.11.1", optional = true }
tetsy-hash-db = { version = "0.15.2", default-features = false }
tetsy-trie-db = { version = "0.22.2", default-features = false }
tetsy-trie-root = { version = "0.16.0", default-features = false }
tp-trie = { version = "2.1.2", path = "../trie", default-features = false }
tet-core = { version = "2.1.2", path = "../core", default-features = false }
panic-handler = { version = "2.1.2", path = "../panic-handler", optional = true }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false }
num-traits = { version = "0.2.8", default-features = false }
rand = { version = "0.7.2", optional = true }
externalities = { version = "2.1.2", path = "../externalities", default-features = false }
smallvec = "1.4.1"
tetcore-std = { version = "2.1.2", default-features = false, path = "../std" }

[dev-dependencies]
hex-literal = "0.3.1"
tp-runtime = { path = "../runtime" }
pretty_assertions = "0.7.2"

[features]
default = ["std"]
std = [
	"codec/std",
	"tetsy-hash-db/std",
	"num-traits/std",
	"tet-core/std",
	"externalities/std",
	"tetcore-std/std",
	"tp-trie/std",
	"tetsy-trie-db/std",
	"tetsy-trie-root/std",
	"log",
	"thiserror",
	"parking_lot",
	"rand",
	"panic-handler",
]
