[package]
name = "node-template"
version = "2.0.0"
authors = ["Anonymous"]
description = "A new FRAME-based Tetcore node, ready for hacking."
edition = "2018"
license = "Unlicense"
build = "build.rs"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node-template"

[dependencies]
structopt = "0.3.8"

tc-cli = { version = "0.8.0", path = "../../../client/cli", features = ["wasmtime"] }
tet-core = { version = "2.0.0", path = "../../../primitives/core" }
tc-executor = { version = "0.8.0", path = "../../../client/executor", features = ["wasmtime"] }
tc-service = { version = "0.8.0", path = "../../../client/service", features = ["wasmtime"] }
tc-telemetry = { version = "2.0.0", path = "../../../client/telemetry" }
tc-keystore = { version = "2.0.0", path = "../../../client/keystore" }
tp-inherents = { version = "2.0.0", path = "../../../primitives/inherents" }
tc-transaction-pool = { version = "2.0.0", path = "../../../client/transaction-pool" }
tp-transaction-pool = { version = "2.0.0", path = "../../../primitives/transaction-pool" }
tc-consensus-aura = { version = "0.8.0", path = "../../../client/consensus/aura" }
tp-consensus-aura = { version = "0.8.0", path = "../../../primitives/consensus/aura" }
tp-consensus = { version = "0.8.0", path = "../../../primitives/consensus/common" }
tc-consensus = { version = "0.8.0", path = "../../../client/consensus/common" }
tc-finality-grandpa = { version = "0.8.0", path = "../../../client/finality-grandpa" }
tp-finality-grandpa = { version = "2.0.0", path = "../../../primitives/finality-grandpa" }
tc-client-api = { version = "2.0.0", path = "../../../client/api" }
tp-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }

# These dependencies are used for the node template's RPCs
tetsy-jsonrpc-core = "15.1.0"
tc-rpc = { version = "2.0.0", path = "../../../client/rpc" }
tp-api = { version = "2.0.0", path = "../../../primitives/api" }
tc-rpc-api = { version = "0.8.0", path = "../../../client/rpc-api" }
tp-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
tp-block-builder = { version = "2.0.0", path = "../../../primitives/block-builder" }
tc-basic-authorship = { version = "0.8.0", path = "../../../client/basic-authorship" }
tetcore-frame-rpc-system = { version = "2.0.0", path = "../../../utils/frame/rpc/system" }
pallet-transaction-payment-rpc = { version = "2.0.0", path = "../../../frame/transaction-payment/rpc/" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "2.0.0", path = "../../../frame/benchmarking" }
frame-benchmarking-cli = { version = "2.0.0", path = "../../../utils/frame/benchmarking-cli" }

node-template-runtime = { version = "2.0.0", path = "../runtime" }

[build-dependencies]
build-script-utils = { version = "2.0.0", path = "../../../utils/build-script-utils" }

[features]
default = []
runtime-benchmarks = [
	"node-template-runtime/runtime-benchmarks",
]
