[package]
name = "tetcore-test-runtime-transaction-pool"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tetcore-test-runtime-client = { version = "2.0.0", path = "../client" }
parking_lot = "0.11.1"
codec = { package = "tetsy-scale-codec", version = "2.0.0" }
tc-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
tc-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
tc-transaction-pool = { version = "2.0.0", path = "../../../primitives/transaction-pool" }
sc-transaction-graph = { version = "2.0.0", path = "../../../client/transaction-pool/graph" }
futures = { version = "0.3.1", features = ["compat"] }
derive_more = "0.99.2"
